from pathlib import Path
p=Path('src/groom-flow.js');s=p.read_text()
s=s.replace('front=.984+.006*Math.sin(v*139)+.003*Math.sin(v*331),a=(1-smooth(v,tip-.018,tip))*(1-smooth(u,front-.024,front))','front=.994+.002*Math.sin(v*139)+.001*Math.sin(v*331),feather=.004+.007*(1-smooth(v,.30,.49)),a=(1-smooth(v,tip-.014,tip))*(1-smooth(u,front-feather,front))')
s=s.replace('rootPoint(side,.971+.033*r,t)','rootPoint(side,.987+.015*r,t)').replace('p.y-=.012+.040*r*Math.sin(PI*t)','p.y-=.010+.025*r*Math.sin(PI*t)')
p.write_text(s)
p=Path('src/eyes.js');s=p.read_text();s=s.replace("import {buildIrisTexture} from './iris.js';","import {buildIrisTexture} from './iris.js';\nimport {applyCorneaShading} from './cornea-shading.js';")
s=s.replace("cornea.userData.exportTransmission=true;","cornea.userData.exportTransmission=true;applyCorneaShading(cornea);")
p.write_text(s)
p=Path('src/load-portrait.js');s=p.read_text().replace("import {applyHairShading} from './hair-shading.js';","import {applyHairShading} from './hair-shading.js';\nimport {applyCorneaShading} from './cornea-shading.js';")
s=s.replace('material.envMapIntensity=2.6;','material.envMapIntensity=.82;material.roughness=.13;applyCorneaShading(material);')
p.write_text(s)
p=Path('src/brows.js');s=p.read_text().replace('i<350','i<440').replace('))/350', '))/440').replace('width=.0115','width=.0140').replace('r=.00031+.00025','r=.00032+.00023');p.write_text(s)
p=Path('src/face-surface.js');s=p.read_text().replace("new THREE.Color('#866257'),.29*G(y-by,.0105", "new THREE.Color('#836055'),.42*G(y-by,.0140");p.write_text(s)
p=Path('src/skin-atlas.js');s=p.read_text().replace('.021*lip*Math.sin','.044*lip*Math.sin').replace('vascular*2.5','vascular*6.0').replace('vascular*1.5','vascular*3.5');p.write_text(s)
print('Pass 31: repaired crown coverage, optical corneal reflections, soft brow density, and fine lip grain.')
