/** Original procedural surface maps; no external image or reference pixels. */
import * as THREE from "three";
const clamp=THREE.MathUtils.clamp;
function hash(x,y){let n=Math.imul(x|0,374761393)+Math.imul(y|0,668265263);n=Math.imul(n^(n>>>13),1274126177);return ((n^(n>>>16))>>>0)/4294967295;}
function texture(data,w,h,{color=false,repeat=1}={}){const t=new THREE.DataTexture(data,w,h);t.colorSpace=color?THREE.SRGBColorSpace:THREE.NoColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(repeat,repeat);t.minFilter=THREE.LinearMipmapLinearFilter;t.magFilter=THREE.LinearFilter;t.generateMipmaps=true;t.needsUpdate=true;return t;}
export function heightNormal(heights,size,strength=1,repeat=1){const d=new Uint8Array(size*size*4);for(let y=0;y<size;y++)for(let x=0;x<size;x++){const left=heights[y*size+(x+size-1)%size],right=heights[y*size+(x+1)%size],down=heights[((y+size-1)%size)*size+x],up=heights[((y+1)%size)*size+x];let nx=(left-right)*strength,ny=(down-up)*strength,nz=1,inv=1/Math.hypot(nx,ny,nz);const i=(y*size+x)*4;d[i]=Math.round((nx*inv*.5+.5)*255);d[i+1]=Math.round((ny*inv*.5+.5)*255);d[i+2]=Math.round((nz*inv*.5+.5)*255);d[i+3]=255;}return texture(d,size,size,{repeat});}
export function skinMicrostructure(){const n=512,h=new Float32Array(n*n),albedo=new Uint8Array(n*n*4),rough=new Uint8Array(n*n*4);for(let y=0;y<n;y++)for(let x=0;x<n;x++){const noise=hash(x,y),broad=hash(x>>3,y>>3);const cx=(x%4)-1.5,cy=(y%4)-1.5,r=Math.hypot(cx+(hash(x>>2,y>>2)-.5)*1.2,cy+(hash((x>>2)+10,y>>2)-.5)*1.2),pore=Math.exp(-r*r/.48);const v=.52+.10*(noise-.5)-.18*pore+.024*Math.sin(x*.42+y*.71);h[y*n+x]=v;const i=(y*n+x)*4,tone=.970+.015*noise-.025*pore-.009*broad;albedo[i]=Math.round(255*tone);albedo[i+1]=Math.round(255*(tone-.006*broad));albedo[i+2]=Math.round(255*(tone-.003*broad));albedo[i+3]=255;rough[i]=rough[i+1]=rough[i+2]=Math.round(255*(.63+.075*pore+.035*noise));rough[i+3]=255;}return {normal:heightNormal(h,n,1.1,8),albedo:texture(albedo,n,n,{color:true,repeat:8}),roughness:texture(rough,n,n,{repeat:8})};}
export function hairSurfaceMaps(heightTexture){const {data,width:n}=heightTexture.image,h=new Float32Array(n*n),albedo=new Uint8Array(n*n*4),rough=new Uint8Array(n*n*4);for(let i=0;i<n*n;i++){const v=data[i*4]/255;h[i]=v;const c=new THREE.Color(v,v,v).convertLinearToSRGB();albedo[i*4]=Math.round(c.r*255);albedo[i*4+1]=Math.round(c.g*255);albedo[i*4+2]=Math.round(c.b*255);albedo[i*4+3]=255;rough[i*4]=rough[i*4+1]=rough[i*4+2]=Math.round(255*(.78+.15*(1-v)));rough[i*4+3]=255;}return{normal:heightNormal(h,n,.7),albedo:texture(albedo,n,n,{color:true}),roughness:texture(rough,n,n)};}
export function hairlineMask(){const n=512,d=new Uint8Array(n*n*4);for(let y=0;y<n;y++)for(let x=0;x<n;x++){const v=y/(n-1),end=.929+.065*hash(x>>1,83),a=1-THREE.MathUtils.smoothstep(v,end-.018,end);const i=(y*n+x)*4;d[i]=d[i+1]=d[i+2]=Math.round(a*255);d[i+3]=255;}const t=texture(d,n,n);t.wrapT=THREE.ClampToEdgeWrapping;return t;}
export function scleraPigment(){const w=256,h=96,d=new Uint8Array(w*h*4);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const u=x/(w-1)*2-1,v=y/(h-1),edge=Math.pow(Math.abs(u),4),upper=Math.pow(v,5),lower=Math.pow(1-v,10),shade=1-.11*upper-.028*lower;const c=new THREE.Color("#e9e0d7").lerp(new THREE.Color("#c69a91"),edge*.36).multiplyScalar(shade);const vein=Math.pow(Math.max(0,Math.sin(v*71+Math.sin(u*19)*4)),36)*Math.pow(Math.abs(u),7)*.045;c.lerp(new THREE.Color("#b37d78"),vein);c.convertLinearToSRGB();const i=(y*w+x)*4;d[i]=Math.round(clamp(c.r*255,0,255));d[i+1]=Math.round(clamp(c.g*255,0,255));d[i+2]=Math.round(clamp(c.b*255,0,255));d[i+3]=255;}return texture(d,w,h,{color:true});}
